site_name: My Docs
theme:
  name: material
nav:
  - Home: index.md
  - About: company.md
site_name: JohnTelford
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
