site_name: John Telford

theme:
  name: material

nav:
  - Home: index.md
  - About: company.md

markdown_extensions:
  - admonition
  
  - pymdownx.details
  
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
