site_name: John Telford

theme:
  name: material
  
  features:
    - navigation.tracking
    - navigation.instant

# page tree
nav:
  - Home: index.md
  
  - Teams:
    - teams.md
    - define.md
    - design.md

  - Company:
    - About: company.md
    - Contact: contact.md

  - Materials for MkDocs:
    - creating site.md
    - diagrams.md

markdown_extensions:
  - admonition
  
  - pymdownx.details
  
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
